compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
mixed_precision: fp16
num_processes: 1  # set to number of GPUs on your machine
num_machines: 1
machine_rank: 0
main_process_ip: null
main_process_port: null
use_cpu: false

# Optional: gradient_accumulation_steps, deepspeed_config, etc. can be added as needed
